### ISSUE TITLE
java.net.BindException: Can't assign requested address

### ISSUE THREAD

**Issue by vicmosin** [facebook/swift#263]
I make an overload testing of my client/server app based on Swift.. After a couple of hundreds iterations I receive:  

```
EXCEPTION, please implement org.jboss.netty.handler.codec.http.HttpChunkAggregator.exceptionCaught() for proper handling.
java.net.BindException: Can't assign requested address
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:458)
	at sun.nio.ch.Net.connect(Net.java:450)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
	at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
	at org.jboss.netty.channel.Channels.connect(Channels.java:634)
	at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
	at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at com.facebook.nifty.client.AbstractClientConnector.connect(AbstractClientConnector.java:42)
	at com.facebook.nifty.client.NiftyClient.connectAsync(NiftyClient.java:184)
	at com.facebook.swift.service.ThriftClientManager.createChannel(ThriftClientManager.java:143)
	at com.facebook.swift.service.ThriftClientManager.createClient(ThriftClientManager.java:216)
	at com.facebook.swift.service.ThriftClientManager.createClient(ThriftClientManager.java:159)
```

After that client fails with: `org.apache.thrift.transport.TTransportException: Failed to connect client channel`

Any ideas? Thank you

**Comment by dain** [comment]
Are you closing the clients?

**Comment by andrewcox** [comment]
This is a common problem that shows up in load testing a TCP service (not unique to swift or even thrift), because if you are talking to a single service at a single IP/port, there is a limit to the # of connections a single client IP can make to a single server IP port, and even if you close the connections promptly, they go into TIME_WAIT state for some time (e.g. I think 60s by default on Linux, although this is tunable to be much shorter).

(Again assuming linux) you can diagnose what's going on by looking at netstat -na and see if you've got a lot of connections in TIME_WAIT, CLOSE_WAIT, etc and googling to find out what can cause those conditions.

**Comment by vicmosin** [comment]
@dain Yes, I do it accordingly to Swift's specs which says that every client connection should be closed and the best way to do it - is to derive from AutoCloseable.

@andrewcox Is there some articles or best practices regarding using different types of transport within the webapp?

**Comment by andrewcox** [comment]
No, this is just a general TCP issue.

If it's what it sounds like it is, most webapps or other backend services in general do not create connections at a high enough rate to hit this problem, so it's not generally something you have to think about in a best practices. It mainly occurs if you are doing load testing, when you make too many connections at too high a rate.

Usually the best fix is to reuse connections instead if you know you're going to talk to the same server. Only close them after the connection has failed. You can even look at how swift's own load generator does this.

Another idea if you are operating on very a reliable network is to adjust the OS's TIME_WAIT timeout.

**Comment by vicmosin** [comment]
Hello again,
many thanks for detailed answer, but after reviewing the load generator I still have a couple of questions...

If I understood right the approach, the idea is to calculate the quantity of open connections. Once it more then `config.operationsPerConnection` - close the connection. Makes sense. 

Further, instead of calling `createClient` every time you need new connection, you call `getNiftyChannel` which is:
1. Marked as deprecated
2. Is simple casting to `RequestChannel`
After that you call `executeInIoThread` and due to comments the code will be executed in the channel thread.

So the questions are:
1. if `getNiftyChannel` is deprecated and it's just a casting, why `RequestChannel` does not have `executeInIoThread`?
2. What is the meaning of 
>code will be executed in the channel thread.
Is it the same thread or new?
3. if the answer to previous question is new thread, so this approach won't work within the web application since it does not have any callbacks, just current execution thread. Am I right?
4. What happens when `getNiftyChannel` returns the channel that was closed by server (by timeout for example)?

Thank you in advance

P.S. As you said there is the second solution - to play with TIME_WAIT, but for me it's more important to understand how slow/fast the process of establishing new connection.

**Comment by vicmosin** [comment]
@andrewcox Could you please give some feedback?

**Comment by andrewcox** [comment]
1) I should have put better comments on why I deprecated the method. NiftyClientChannel used to be the only channel type, but now Swift is only promising that the client is backed by a RequestChannel, so it doesn't make sense to provide a getNiftyChannel(). However, if you created the client and you know it is backed by a NiftyClientChannel, just call getRequestChannel and cast the result. 

2) The IO thread is a pool maintained by swift. It is where data is sent and received for a channel. It is a one-to-many relationship: a channel is tied to a specific IO thread, but that IO thread can manage lots of channels. Since the IO thread is where we'll notice a response came back from the server, it is where the callback for success/failure of client calls happens (unless you explicitly specify an executor to run these on, which the load generator does not).

That means that all the calls we make after the initial set filling the pipeline will happen on the IO thread. So it's convenient to make the calls to fill the pipeline on the IO thread as well to avoid multi-threading issues.

3) The discussion started around how to avoid creating too many connections to the same service from the same client, too quickly. If you are making sync calls (no callbacks) that's fine, the point is if you are making a TON of connections very quickly, you can get this error, so try to reuse connections instead where possible.

4) In this case, the next send will fail, and we'll handle this by opening a new connection.
