### ISSUE TITLE
ListThriftCodec uses wrong codec during converting generics structure

### ISSUE THREAD

**Issue by vicmosin** [facebook/swift#269]
Object (constructor quit difficult, but it's just a conversion between two types of objects):
```
@ThriftStruct
@NoArgsConstructor
public final class PagedList<T> implements Serializable {

    private int totalPages;

    private List<T> content;

    public <P, R extends T> PagedList(Page<P> page, Function<P, T> mapper) {
        this.totalPages = page.getTotalPages();
        this.content = page.getContent().stream().map(item -> mapper.apply(item)).collect(Collectors.toList());
    }

    @ThriftField(1)
    public int getTotalPages() {
        return totalPages;
    }

    @ThriftField
    public void setTotalPages(int totalPages) {
        this.totalPages = totalPages;
    }

    @ThriftField(2)
    public List<T> getContent() {
        return content;
    }

    @ThriftField
    public void setContent(List<T> content) {
        this.content = content;
    }
}
```
Client call:
```
try (BusinessThriftService businessService = clientManager.createClient(connector, BusinessThriftService.class).get()) {
			return businessService.findByName(name, page.getPageNumber(), page.getPageSize());
		} catch (Exception e) {
			throw new ThriftException(e.getMessage(), e);
		}
```
where `businessService.findByName` looks like that :
```
public PagedList<Business> findByName(String name, int page, int size) throws DataAccessException {
		try {
			PagedList<Business> t = new PagedList<>(businessRepository.findByName(name, new PageRequest(page, size)), item -> businessDtoMapper.dtoOf(item));
			return t;
		} catch (Exception e) {
			throw new DataAccessException(e.getMessage());
		}
	}
```

Once I run it, I receive `java.lang.ClassCastException` since somehow inside swift the `ListThriftCodec`'s codec is wrong type (of other thrift structure).
Are there any special tips for generics?

**Comment by bgould** [comment]
@vicmosin 

I've come across this type of problem before.  It was a joy to debug.

Summary of what might be happening -

Swift uses some google library to glean type parameter information for generics at runtime beyond what reflection usually allows, iirc it does this by doing things like parsing the actual bytes of the loaded class to get the extra information available if you compiled with the debug option (which is quite common I suppose).  

If it is available, the toString() of the type info ends up being something like `List<Foo>`

If it is not available the toString() is something like `List<?>`

When the `ConcurrentCachingLoader` (or whatever the data structure is called that stores the `ThriftCodec` instances for each type) comes across the `List<?>` type the first time it gets cached, keyed off of the `ThriftType`.  If you have another `List` structure in your program that also has this sort of type erasure with a different type parameter, it will also be resolved as a `List<?>` resulting in a cache hit, even though the type parameter is actually different.

Its possible that since the lambda in your constructor results in an `invokedynamic` call site that is resolved at runtime, the google library can't ascertain what the original generic type parameter was.  Or there could be erasure for some other reason... I'm not really familiar with the specific quirks of that library.

The fix that I used for this is to add an extra type check in equals() and hashCode() for `ThriftType` class for SET, LIST, and MAP structures.  I have an open pull request that includes it (https://github.com/facebook/swift/pull/257), you may want to try to apply this commit and build from source to see if it solves the problem:

https://github.com/bgould/swift/commit/ce9675bd372db3b6ffbc073e9237d5fec2071998

I'd be interested to know if this get things working for you.

**Comment by vicmosin** [comment]
@bgould 
Hi, thanks a lot for your response. I tried your change at `ThriftType` and still have the same issue. I believe that the main reason why your change didn't fix it because of my object's structure - the generic field `content` is  field and the whole class is a container which is not implements `Iterable`. So your additional check inside `shouldHaveValueType` just skipped.

Still waiting for some response from dev team)

**Comment by vicmosin** [comment]
So it seems that thrift has issues with reflection...
The following construction solves the problem:
```
@ThriftStruct
@NoArgsConstructor
public class PagedList<T> implements Serializable {

    private int totalPages;

    public PagedList(Page page) {
        this.totalPages = page.getTotalPages();
    }

    @ThriftField(1)
    public int getTotalPages() {
        return totalPages;
    }

    @ThriftField
    public void setTotalPages(int totalPages) {
        this.totalPages = totalPages;
    }
}
@ThriftStruct
@NoArgsConstructor
public final class UserPagedList extends PagedList<User> {

    private List<User> content;

    public UserPagedList(Page page, List<User> content) {
        this.totalPages = page.getTotalPages();
        this.content = content;
    }
}
```
Not so elegant since you have to declare such class per each of your models, but at least works

**Comment by qq291462491** [comment]
Now, I met the same problem, see also can only use this kind of not elegant method
