### ISSUE TITLE
Multiple @ThriftMethod-annotated methods named

### ISSUE THREAD

**Issue by renyankankan** [facebook/swift#291]
![123](https://cloud.githubusercontent.com/assets/8908595/12193704/6bff109e-b625-11e5-9d9c-6fb54a310018.png)

so, it makes all the @ThriftMethod-annotated methods must be different,  even they are in different ThriftService, why?

**Comment by bgould** [comment]
They discuss that in the documentation here:

https://github.com/facebook/swift/tree/master/swift-service#thrift-server

*Additionally, Swift supports mix in style servers where multiple Thrift services can be exported on the same port without having to use Java class inheritance. The only restriction is that the services must have non-overlaping method names.*

If you want to be able to have overlapping names, instead of using "mix in style servers" you can use TMultiplexedProtocol which also allows you to export multiple services from the same endpoint, but uses namespacing so you can have overlapping names
